name = "my-library"
main = "build/worker/shim.mjs"
compatibility_date = "2025-06-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "my-library"
database_id = "9ba869d4-5138-41b8-9a1f-040ee417783b"
